version: '3'
services:
  db2:
    image: ibmcom/db2
    container_name: mydb2
    privileged: true
    ports:
      - '50000:50000'
    volumes:
      - ./database:/database
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
      - DBNAME=testdb
volumes:
  database:
