CREATE TABLE stores(
	store_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	store_name VARCHAR(150) NOT NULL,
	address_line_1 VARCHAR(255) NOT NULL,
	address_line_2 VARCHAR(100),
	city_id INT NOT NULL,
	state_id INT NOT NULL,
	zip_code VARCHAR(6),
	zip_code_1 VARCHAR(6),
	zip_code_2 VARCHAR(6),
	zip_code_3 VARCHAR(6),
	zip_code_4 VARCHAR(6),
	PRIMARY KEY (store_id)
);
